sudo: required

services:
- docker

language: java

before_install:
- sudo service docker restart ; sleep 10
- chmod 600 .buildscript/brooklyn.properties
- docker run -d --name=host1 -e ROOT_PASS="root" tutum/ubuntu:trusty
- docker run -d --name=host2 -e ROOT_PASS="root" tutum/ubuntu:trusty
- docker run -d --name=host3 -e ROOT_PASS="root" tutum/ubuntu:trusty
- docker run -d --name=brooklyn --link host1 --link host2 --link host3 -p 8081:8081 -v `pwd`/.buildscript/brooklyn.properties:/root/.brooklyn/brooklyn.properties --entrypoint bin/brooklyn.sh googlielmo/clocker launch --catalogAdd `pwd`/seaclouds-catalog.bom
- docker ps -a
- docker inspect brooklyn

install:
- mvn install -DskipTests=true -X

branches:
  except:
  - travis
env:
  global:
  - secure: "q6oLIb4TpyVxy6jcauijVcGkkTr3xe5dfcII5yJs48r2FzcZeAYqPvifb9G9tlOiK5igXJrEa2GmNytlI9NijOIAt8BBV34xIovwkupwJ9qGAxG2E5hHbAjGiRaICTglkH+psgaPuPe4W8UgmWCSNt9bM12F1bVHsXXftWx/880="
  - secure: "VYSXB7Myuqbkyt9vjiro09R6e44G2xAie8Q8lYfJreghp7kTIUeH3cCY9gMRb8pMiYadVtF01hzJWaf6PaApScNivmMUkvzGGvfnRX1FbBoxL9CIhkZkmofoyvqiobE4moZpDl6wje7APAch2b/D9Q4CmNQf7eBFic9XissQqA4="

cache:
  directories:
  - $HOME/.m2

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/616eadc01d54389d624f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
